version: "3.8"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: backend:medusa
    container_name: medusa-server
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://cache
      NODE_ENV: development
      JWT_SECRET: supersecret
      COOKIE_SECRET: supersecret
      MEILISEARCH_HOST: meilisearch
      MEILISEARCH_API_KEY: ${MEILISEARCH_API_KEY}
    ports:
      - "9000:9000"
      - "7000:7000"
      - "7001:7001"

  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  meilisearch:
    image: getmeili/meilisearch:v1.5
    volumes:
      - ~/apps/meilisearch:/data.ms
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700"]
      interval: 10s
      timeout: 5s
      retries: 5
